"""results/ → paper/tables/*.tex — KHÔNG gõ số tay.

    python scripts/build_tables.py --config configs/exp_smoke.yaml
    python scripts/build_tables.py --config configs/exp_main.yaml

Số liệu chảy MỘT CHIỀU: `configs/` → `scripts/` → `results/` → `paper/`
(ke-hoach-trien-khai.md §0 nguyên tắc 1). Bảng trong bản thảo được **sinh** từ CSV; một
số không truy được về một ô CSV là `[PLACEHOLDER]` và không được vào bản thảo.

| Sinh ra | Từ | Nội dung |
|---|---|---|
| `table2_dp_vs_bruteforce.tex` | `results/exact/dp_vs_bruteforce.csv` | DP vs vét cạn |
| `table3_main_grid.tex` | `results/main/summary.csv` + `mask_identity.csv` | gap · hit-rate · NFE · Dice · **mask-identity** |
| `table4_ablation.tex` | `results/ablation/summary.csv` (+ `results/stats/`) | ablation QIGOA |
| `table5_ceiling.tex` | `results/ceiling/summary.csv` (+ `results/unet/`) | thang bậc trần |

⚠️ **Bảng II (DP vs vét cạn) là bảng ĐẦU TIÊN của bản thảo** — một bảng toán học, không
buộc tội ai. **Bảng I (trắc lượng thư mục) xuống Supplementary**: nếu bảng đầu tiên editor
nhìn thấy là *"chúng tôi đếm N bài không cite X"*, bài bị phân loại **meta-science** và
out-of-scope ngay tại đó (ke-hoach-trien-khai.md §4, quyết định đóng khung 3).

⚠️ Mọi bảng sinh từ dữ liệu synthetic được đóng dấu **[PLACEHOLDER]** ngay trong caption.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

from _common import (
    ROOT,
    data_source,
    load_config,
    parse_args,
    read_results_csv,
    resolve_output_dir,
    section,
)

PLACEHOLDER_TEX = (r"\textbf{[PLACEHOLDER --- synthetic phantoms, NOT results "
                   r"(CLAUDE.md IRON RULE 1/3)]} ")


def _esc(s) -> str:
    return (str(s).replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")
            .replace("#", r"\#"))


def _tex(df: pd.DataFrame, caption: str, label: str, ph: bool, note: str = "") -> str:
    """Bảng LaTeX. Header do ta viết (đã sẵn sàng LaTeX, có thể chứa toán) ⇒ KHÔNG escape;
    ô dữ liệu đến từ CSV (có `_` như `oracle_levelset`) ⇒ escape TỪNG Ô."""
    cap = (PLACEHOLDER_TEX if ph else "") + caption
    if note:
        cap += " " + note
    d = df.copy()
    for c in d.columns:
        # KHÔNG dùng `dtype == object`: pandas mới suy ra dtype `str` cho cột chuỗi ⇒ test
        # đó âm thầm trượt và `oracle_levelset` lọt ra ngoài chưa escape ⇒ vỡ LaTeX.
        if not pd.api.types.is_numeric_dtype(d[c]):
            d[c] = d[c].map(_esc)
    cols = "l" + "r" * (len(d.columns) - 1)
    body = d.to_latex(index=False, escape=False, column_format=cols, float_format="%.4f",
                      na_rep="---")
    return (f"% GENERATED by scripts/build_tables.py — DO NOT EDIT BY HAND.\n"
            f"% Every number traces to a CSV cell (CLAUDE.md §5.3).\n"
            f"\\begin{{table}}[t]\n\\centering\n\\caption{{{cap}}}\n"
            f"\\label{{{label}}}\n{body}\\end{{table}}\n")


def _write(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"  ✓ {path.relative_to(ROOT)}")
    return path


def _load(p: Path) -> pd.DataFrame:
    return read_results_csv(p) if p.exists() else pd.DataFrame()


def main() -> int:
    args = parse_args(__doc__.splitlines()[0]).parse_args()
    cfg, _ = load_config(args.config)
    scfg = section(cfg, "stats")
    ph = data_source(cfg) == "synthetic"

    main_dir = ROOT / (scfg.get("main_dir") or cfg.get("output_dir") or "results/main")
    exact_dir = ROOT / ((cfg.get("exact_check") or {}).get("output_dir") or "results/exact")
    abl_dir = ROOT / ((cfg.get("ablation") or {}).get("output_dir") or "results/ablation")
    ceil_dir = ROOT / (scfg.get("ceiling_dir")
                       or (cfg.get("ceiling") or {}).get("output_dir") or "results/ceiling")
    unet_dir = ROOT / (scfg.get("unet_dir")
                       or (cfg.get("unet") or {}).get("output_dir") or "results/unet")
    out_dir = resolve_output_dir({}, args.output, "paper/tables")
    k_primary = int((cfg.get("stats") or {}).get("k_primary", 4))
    rule = str((cfg.get("stats") or {}).get("decoding_primary", "brightest"))
    print(f"[tables] → {out_dir}")

    # ---- Bảng II — DP vs vét cạn (bảng TOÁN HỌC, mở đầu bản thảo) ---------- #
    d = _load(exact_dir / "dp_vs_bruteforce.csv")
    if not d.empty:
        g = (d.groupby("k")
             .agg(n_images=("patient_id", "nunique"),
                  max_abs_diff=("abs_diff", "max"),
                  mask_identical=("mask_identical", "mean"),
                  passed=("pass", "mean"),
                  t_dp_ms=("t_dp_s", lambda s: 1000 * s.mean()),
                  t_brute_ms=("t_brute_s", lambda s: 1000 * s.mean()))
             .reset_index())
        g["brute/DP"] = g["t_brute_ms"] / g["t_dp_ms"]
        # |Δf| ~ 1e-16: %.4f sẽ in "0.0000" và trông như ta làm tròn cho đẹp ⇒ khoa học.
        g["max_abs_diff"] = g["max_abs_diff"].map(lambda v: f"{float(v):.2e}")
        g.columns = ["$k$", "images", r"max $|\Delta f|$", "mask identical",
                     "pass rate", "DP (ms)", "brute force (ms)", "ratio"]
        _write(out_dir / "table2_dp_vs_bruteforce.tex", _tex(
            g, "Exact dynamic programming versus exhaustive search on the Kapur "
               "objective. Agreement criterion (pre-registered): $|f_{DP}-f_{brute}| "
               r"\leq 10^{-9}$ \emph{and} an identical induced mask after threshold "
               "canonicalisation. No novelty is claimed for the exact solver "
               "(Menotti et al., CIARP 2015).",
            "tab:dp_vs_brute", ph,
            note="Runtime is reported for completeness only; the currency of this study "
                 "is NFE and complexity, not wall-clock."))

    # ---- Bảng III — lưới chính ------------------------------------------- #
    s = _load(main_dir / "summary.csv")
    ident = _load(main_dir / "mask_identity.csv")
    if not s.empty:
        f = s[(s["decode_rule"] == rule) & (s["k"] == k_primary)]
        if f.empty:
            f = s[s["decode_rule"] == rule]
        keep = ["method", "n_patients", "relative_gap_mean", "hit_rate", "nfe_mean",
                "dice_median", "dice_ci_low", "dice_ci_high", "hd95_median",
                "n_components_median", "empty_mask_rate"]
        t = f[[c for c in keep if c in f.columns]].copy()
        t.columns = ["Method", "$n$", "rel. gap", "hit rate", "NFE", "Dice (med)",
                     "CI low", "CI high", "HD95 (med)", "\\#CC (med)",
                     "empty-mask"][:len(t.columns)]
        note = ""
        if not ident.empty:
            i = ident[(ident["decode_rule"] == rule) & (ident["k"] == k_primary)]
            if not i.empty:
                note = (f"Mask-identity rate at $k={k_primary}$: "
                        f"{float(i['mask_identity_rate'].mean()):.3f} --- the fraction of "
                        f"(patient, seed) cells in which \\emph{{every}} metaheuristic "
                        f"returns a byte-for-byte identical binary mask.")
        _write(out_dir / "table3_main_grid.tex", _tex(
            t, f"Equal-NFE grid at the pre-registered primary configuration "
               f"($k={k_primary}$, decoding rule \\texttt{{{_esc(rule)}}}). Dice is "
               r"reported as median with 95\% bootstrap CI (Dice is bounded and skewed, "
               "so mean$\\pm$std would misrepresent it). Empty-mask rate is reported as "
               "an independent result, not filtered out.",
            "tab:main_grid", ph, note))

    # ---- Bảng IV — ablation ---------------------------------------------- #
    a = _load(abl_dir / "summary.csv")
    if not a.empty:
        f = a[a["k"] == k_primary] if (a["k"] == k_primary).any() else a
        keep = ["method", "n_patients", "relative_gap_mean", "hit_rate", "nfe_mean",
                "dice_median", "dice_ci_low", "dice_ci_high", "hd95_median"]
        t = f[[c for c in keep if c in f.columns]].copy()
        t.columns = ["Variant", "$n$", "rel. gap", "hit rate", "NFE", "Dice (med)",
                     "CI low", "CI high", "HD95 (med)"][:len(t.columns)]
        _write(out_dir / "table4_ablation.tex", _tex(
            t, "Component ablation of QIGOA under an identical NFE budget and "
               "identical values for every other hyper-parameter. Equivalence must be "
               r"read from the 90\% CI and $\Delta_{ach}$ in \texttt{results/stats/}, "
               "never from $p>0.05$.",
            "tab:ablation", ph,
            note="The prediction that the quantum component contributes $\\approx 0$ "
                 "Dice was registered before any of these numbers existed."))

    # ---- Bảng V — thang bậc trần ----------------------------------------- #
    c = _load(ceil_dir / "summary.csv")
    u = _load(unet_dir / "summary.csv")
    if not c.empty:
        keep = ["method", "method_class", "include_zero_bg", "n_patients", "dice_median",
                "dice_ci_low", "dice_ci_high", "hd95_median", "empty_mask_rate"]
        t = c[[k for k in keep if k in c.columns]].copy()
        if not u.empty:
            # U-Net không có trục include_zero_bg (nó không đọc histogram) ⇒ 'na'.
            uu = u.reindex(columns=[k for k in keep if k in u.columns or k == "include_zero_bg"])
            uu["include_zero_bg"] = "na"
            t = pd.concat([t, uu], ignore_index=True)
        t = t.sort_values("dice_median")
        t.columns = ["Method", "Class", "bg", "$n$", "Dice (med)", "CI low", "CI high",
                     "HD95 (med)", "empty-mask"][:len(t.columns)]
        _write(out_dir / "table5_ceiling.tex", _tex(
            t, "Ceiling ladder on a common Dice axis. Class C rows \\emph{use "
               "test-time ground truth}: they are unreachable upper bounds, not "
               "methods. Class B rows (2D U-Net, the one-parameter threshold) are "
               "scored strictly out-of-fold under patient-level nested CV.",
            "tab:ceiling", ph,
            note="We do not claim to establish this ceiling: an oracle Dice bound for "
                 "thresholding on BraTS FLAIR is already published (Fran\\c{c}ois \\& "
                 "Tinarrage, JMIV 2026), and the level-set optimality result is due to "
                 "Lipton et al. (2014) / RankSEG (2023). Our contribution is the "
                 "\\emph{decomposition}."))

    print("[tables] xong. ⚠️ Bảng I (trắc lượng thư mục) là khảo sát TAY (2 coder, "
          "Cohen's κ) ⇒ KHÔNG sinh từ script này, và nằm ở Supplementary.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
